#!/usr/bin/env bash
# script to fix nginx server that won't shut off via daemon manager
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
pkill nginx
service nginx start
