#!/usr/bin/env bash
# script to fix nginx server that won't shut off via daemon manager
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
